lib/deer_storage_web/router.ex
defmodule DeerStorageWeb.Router do
  use DeerStorageWeb, :router

  import Phoenix.LiveDashboard.Router

  alias DeerStorageWeb.LayoutView

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DeerStorageWeb.LocalePlug
    plug DeerStorageWeb.GetCurrentSubscriptionPlug
  end

  pipeline :protected,
    do: plug(Pow.Plug.RequireAuthenticated, error_handler: DeerStorageWeb.AuthErrorHandler)

  pipeline :not_authenticated,
    do: plug(Pow.Plug.RequireNotAuthenticated, error_handler: DeerStorageWeb.AuthErrorHandler)

  pipeline :admin, do: plug(DeerStorageWeb.EnsureRolePlug, :admin)
  pipeline :navigation_tracked, do: plug(NavigationHistory.Tracker, history_size: 1)

  scope "/", DeerStorageWeb do
    pipe_through [:browser, :protected]

    get "/files/record/:record_id/:file_id", DeerFilesController, :download_record

    live_session :default_live_without_navigation,
      root_layout: {DeerStorageWeb.LayoutView, :without_navigation} do
      live "/dashboard", DeerDashboardLive.Index
      live "/records/:table_id", DeerRecordsLive.Index
    end

    resources "/registration", RegistrationController, singleton: true, only: [:edit, :update]

    put "/registration/switch_subscription_id/:subscription_id",
        RegistrationController,
        :switch_subscription_id

    put "/registration/reset_subscription_id", RegistrationController, :reset_subscription_id

    resources "/session", SessionController, singleton: true, only: [:delete]
    resources "/invitation", InvitationController, only: [:new, :create]

    resources "/users", UserController, only: [:index] do
      put "/unlink/:subscription_id", UserController, :unlink

      put "/toggle_permission/:subscription_id/:permission_key",
          UserController,
          :toggle_permission
    end

    scope "/admin", Admin, as: :admin do
      pipe_through [:admin]

      live_dashboard "/phoenix",
        metrics: DeerStorageWeb.Telemetry,
        metrics_history: {DeerStorageWeb.MetricsStorage, :metrics_history, []},
        ecto_repos: [DeerStorage.Repo]

      live "/dashboard", DashboardLive.Index

      post "/users/search", UserController, :search

      resources "/users", UserController do
        resources "/subscription_links", UserSubscriptionLinkController, only: [:delete, :create]
        put "/subscription_links/reset", UserSubscriptionLinkController, :reset

        put "/subscription_links/make_current/:subscription_id",
            UserSubscriptionLinkController,
            :make_current

        put "/toggle_admin", UserController, :toggle_admin
        put "/log_out_from_devices", UserController, :log_out_from_devices
        put "/confirm_user", UserController, :confirm_user
      end

      post "/subscriptions/search", SubscriptionController, :search

      resources "/subscriptions", SubscriptionController do
        resources "/subscription_links", UserSubscriptionLinkController, only: [:delete, :create]
      end
    end
  end

  scope "/", DeerStorageWeb do
    pipe_through [:browser, :not_authenticated, :navigation_tracked]

    resources "/session", SessionController, singleton: true, only: [:new, :create]
    resources "/registration", RegistrationController, singleton: true, only: [:new, :create]
    resources "/reset-password", ResetPasswordController, only: [:new, :create, :edit, :update]
    resources "/invitation", InvitationController, only: [:edit, :update]
  end

  scope "/", DeerStorageWeb do
    pipe_through [:browser, :navigation_tracked]

    live_session :default_without_navigation_for_shared_record,
      root_layout: {DeerStorageWeb.LayoutView, :without_navigation} do
      live "/share/:subscription_id/:shared_record_uuid", SharedRecordsLive.Show
    end

    get "/:subscription_id/shared_record/:shared_record_id/:file_id",
        SharedRecordFilesController,
        :download_file_from_shared_record

    get "/:subscription_id/shared_file/:shared_file_id/:file_id",
        SharedRecordFilesController,
        :download_file_from_shared_file

    post "/change_language", ChangeLanguageController, :change_language

    resources "/confirm-email", ConfirmationController, only: [:show]

    get "/", PageController, :index
  end
end

lib/deer_storage_web/views/layout_view.ex
defmodule DeerStorageWeb.LayoutView do
  import DeerStorage.FeatureFlags, only: [registration_enabled?: 0]
  use DeerStorageWeb, :view
  use Phoenix.Component

  def available_languages_and_locales(), do: [{"Polski", "pl"}, {"English", "en"}]

  def maybe_active_dashboard_link(socket, header_str) do
    header_str = if header_str, do: "🏠 " <> header_str

    class =
      case socket.view do
        DeerStorageWeb.DeerDashboardLive.Index -> "navbar-item has-text-weight-bold is-active"
        _ -> "navbar-item has-text-weight-bold"
      end

    link = Routes.live_path(socket, DeerStorageWeb.DeerDashboardLive.Index)
    content_tag(:a, header_str, href: link, class: class)
  end

  def maybe_active_records_link(socket, %{id: id} = dt, id) do
    class = "navbar-item is-active"
    path = Routes.live_path(socket, DeerStorageWeb.DeerRecordsLive.Index, dt.id)

    text = "#{dt.name} (#{dt.count})"

    content_tag(:a, text, href: path, class: class)
  end

  def maybe_active_records_link(socket, dt, _) do
    class = "navbar-item"
    path = Routes.live_path(socket, DeerStorageWeb.DeerRecordsLive.Index, dt.id)
    text = "#{dt.name} (#{dt.count})"

    content_tag(:a, text, href: path, class: class)
  end

  def title(conn) do
    case conn.assigns[:title] do
      nil -> gettext("DeerStorage")
      title -> title
    end
  end

  def compact_tables_to_ids_and_names(deer_tables) do
    Enum.map(deer_tables, fn %{id: id, name: name} -> %{id: id, name: name} end)
  end

  def header_text(%{assigns: %{current_subscription_is_expired: true}}),
    do: gettext("DATABASE EXPIRED")

  def header_text(%{assigns: %{current_subscription: %{name: name}}}), do: name
  def header_text(%{assigns: %{current_user: %{name: name}}}), do: name
  def header_text(_), do: gettext("DeerStorage")

  def render_navigation(%{assigns: %{current_user: nil}} = conn),
    do: render("navigation_guest.html", conn: conn)

  def render_navigation(
        %{assigns: %{current_user: %{role: "admin"}, current_subscription: nil}} = conn
      ) do
    render("navigation_admin.html", conn: conn)
  end

  def render_navigation(conn), do: render("navigation_user.html", conn: conn)
end

lib/deer_storage_web/templates/layout/app.html.heex
<%= @inner_content %>

lib/deer_storage_web/templates/layout/app.html.leex
<%= @inner_content %>

lib/deer_storage_web/templates/layout/navigation_admin.html.eex
<nav class="navbar is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
      <%= link(
          gettext("Admin Panel"),
          to: Routes.admin_live_path(@conn, DeerStorageWeb.Admin.DashboardLive.Index),
          class: "navbar-item") %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navigation">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navigation" class="navbar-menu">
    <div class="navbar-start">
      <%= link(gettext("Users"), to: Routes.admin_user_path(@conn, :index), class: "navbar-item") %>
      <%= link(gettext("Databases"), to: Routes.admin_subscription_path(@conn, :index), class: "navbar-item") %>
      </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= link gettext("Phoenix LiveDashboard"), to: Routes.live_dashboard_path(@conn, :home), method: :get, class: "button is-black navbar-item" %>
          <%= link gettext("Settings"), to: Routes.registration_path(@conn, :edit), method: :get, class: "button is-black navbar-item" %>
          <%= link gettext("Sign out"), to: Routes.session_path(@conn, :delete), method: :delete, class: "button is-link navbar-item" %>
        </div>
      </div>
    </div>
  </div>
</nav>

<script type="text/javascript">
  window.hook_navbar_burger();
</script>

lib/deer_storage_web/templates/layout/navigation_guest.html.eex
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand is-vcentered">
    <span class="navbar-item">
      <a href="/">
        <strong>
          🦌 <%= gettext("DeerStorage") %>
        </strong>
      </a>
      &nbsp;
      <div class="field">
        <div class="control">
          <div class="select">
            <% current_locale = Gettext.get_locale(DeerStorageWeb.Gettext) %>

            <%= form_for DeerStorageWeb.Endpoint, Routes.change_language_path(DeerStorageWeb.Endpoint, :change_language), fn _f -> %>
              <select onChange="this.form.submit()" name="locale">
                <%= Enum.map(available_languages_and_locales(), fn {language, ^current_locale} -> %>
                  <option value="<%= current_locale %>" selected><%= language %></option>
                <% {language, locale} -> %>
                  <option value="<%= locale %>"><%= language %></option>
                <% end) %>
              </select>
            <% end %>
          </div>
        </div>
      </div>
    </span>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navigation">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navigation" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= if registration_enabled?() do %>
            <a class="button is-primary" href="<%= Routes.registration_path(DeerStorageWeb.Endpoint, :new) %>"> <strong><%= gettext("Register") %></strong> </a>
          <% end %>

          <%= link gettext("Sign in"), to: Routes.session_path(DeerStorageWeb.Endpoint, :new), class: "button is-light" %>
        </div>
      </div>
    </div>
  </div>
</nav>

<script type="text/javascript">
  window.hook_navbar_burger();
</script>

lib/deer_storage_web/templates/layout/navigation_user.html.eex
<%= if @conn.assigns.current_subscription do
      live_render(
        @conn,
        DeerStorageWeb.SubscriptionNavigationLive,
        container: {:div, class: "navbar is-dark"},
        session: %{
          "header_text" => header_text(@conn),
          "subscription_id" => @conn.assigns.current_subscription.id,
          "subscription_tables" => compact_tables_to_ids_and_names(@conn.assigns.current_subscription.deer_tables),
          "storage_limit_kilobytes" => @conn.assigns.current_subscription.storage_limit_kilobytes,
          "locale" => @conn.assigns.locale
        }
      )
    else
      live_render(
        @conn,
        DeerStorageWeb.SubscriptionNavigationLive,
        container: {:div, class: "navbar is-dark"},
        session: %{
          "missing_subscription" => true,
          "locale" => @conn.assigns.locale
        }
      )
end %>

lib/deer_storage_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tag() %>
    <title><%= title(@conn) %></title>
    <link rel="stylesheet" href={Routes.static_path(@conn, "/css/app.css")}/>
    <script type="text/javascript" src={Routes.static_path(@conn, "/js/app.js")}></script>
  </head>
  <body>
    <main role="main">
      <%= render_navigation(@conn) %>

      <%= if @flash != %{} do %>
        <div role="alert" class="help is-size-6 is-danger"><%= Phoenix.Flash.get(@flash, :error) %></div>
        <div role="alert" class="help is-size-6 is-success"><%= Phoenix.Flash.get(@flash, :info) %></div>
        <div role="alert" class="help is-size-6 is-info"><%= Phoenix.Flash.get(@flash, :notice) %></div>
      <% end %>

      <%= @inner_content %>
    </main>
  </body>
</html>

lib/deer_storage_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tag() %>
    <title><%= title(@conn) %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <main role="main">
      <%= render_navigation(@conn) %>

      <%= if @flash != %{} do %>
        <div role="alert" class="help is-size-6 is-danger"><%= Phoenix.Flash.get(@flash, :error) %></div>
        <div role="alert" class="help is-size-6 is-success"><%= Phoenix.Flash.get(@flash, :info) %></div>
        <div role="alert" class="help is-size-6 is-info"><%= Phoenix.Flash.get(@flash, :notice) %></div>
      <% end %>

      <%= @inner_content %>
    </main>
  </body>
</html>

lib/deer_storage_web/templates/layout/without_navigation.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tag() %>
    <title><%= title(@conn) %></title>
    <link rel="stylesheet" href={Routes.static_path(@conn, "/css/app.css")}/>
    <script type="text/javascript" src={Routes.static_path(@conn, "/js/app.js")}></script>
  </head>
  <body>
    <main role="main">
      <%= if @flash != %{} do %>
        <div role="alert" class="help is-size-6 is-danger"><%= Phoenix.Flash.get(@flash, :error) %></div>
        <div role="alert" class="help is-size-6 is-success"><%= Phoenix.Flash.get(@flash, :info) %></div>
        <div role="alert" class="help is-size-6 is-info"><%= Phoenix.Flash.get(@flash, :notice) %></div>
      <% end %>

      <%= @inner_content %>
    </main>
  </body>
</html>

lib/deer_storage_web/templates/layout/without_navigation.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tag() %>
    <title><%= title(@conn) %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <main role="main">
      <%= if @flash != %{} do %>
        <div role="alert" class="help is-size-6 is-danger"><%= Phoenix.Flash.get(@flash, :error) %></div>
        <div role="alert" class="help is-size-6 is-success"><%= Phoenix.Flash.get(@flash, :info) %></div>
        <div role="alert" class="help is-size-6 is-info"><%= Phoenix.Flash.get(@flash, :notice) %></div>
      <% end %>

      <%= @inner_content %>
    </main>
  </body>
</html>